workers:
    # start mariadb through docker and webpack dev-server using default port or first available port
    custom_workers:
        cmd: ['./.symfony.workers.sh']
        
    # # built-in command that run npm dev server to compile assets and hot reload
    # npm_dev_server:
    #     cmd: ['npm', 'run', 'dev-server']

    # # start docker compose to run the local mariadb instance
    # docker_compose: ~